<?php

namespace Nepchure\Test\Models;

use Themosis\Facades\PostType;


class CPTTrials extends EntityCPT
{
    const CPTName = 'trials';
    const CPTIcon = 'dashicons-groups';

    private $CPTInstance;

    public function __construct()
    {
        $this->makePostType();
        $this->addCustomFields();

        add_filter('acf/fields/google_map/api', [$this, 'addGoogleMapKey'] );
        add_action('acf/load_field/key=trial_short_name_key', [ $this, 'autoPopulateShortName' ]);
    }

    /**
     * Register Post Type $CPTname
     */


    protected function makePostType()
    {
        $this->CPTInstance = PostType::make(self::CPTName, 'Trials', 'trial')->set([
            'description' => '',
            'public' => true,
            'publicly_queryable' => true,
            'show_ui' => true,
            'show_in_rest' => false,
            'rest_base' => '',
            'has_archive' => true,
            'show_in_menu' => true,
            'exclude_from_search' => false,
            'capability_type' => 'post',
            'map_meta_cap' => true,
            'hierarchical' => false,
            'rewrite' => [ 'slug' => self::CPTName, 'with_front' => true ],
            'query_var' => true,
            'menu_icon' => self::CPTIcon,
            'supports' => [ 'title', 'thumbnail' ],
            'labels' => [
                'name'                  => __( 'Trials', NPC_TD ),
                'singular_name'         => __( 'Trial', NPC_TD ),
                'menu_name'             => __( 'Trials', NPC_TD ),
                'name_admin_bar'        => __( 'Trial', NPC_TD ),
                'archives'              => __( 'Trial Archives', NPC_TD ),
                'attributes'            => __( 'Trial Attributes', NPC_TD ),
                'parent_item_colon'     => __( 'Parent trial:', NPC_TD ),
                'all_items'             => __( 'All trials', NPC_TD ),
                'add_new_item'          => __( 'Add New trial', NPC_TD ),
                'add_new'               => __( 'Add New', NPC_TD ),
                'new_item'              => __( 'New trial', NPC_TD ),
                'edit_item'             => __( 'Edit trial', NPC_TD ),
                'update_item'           => __( 'Update trial', NPC_TD ),
                'view_item'             => __( 'View trial', NPC_TD ),
                'view_items'            => __( 'View trials', NPC_TD ),
                'search_items'          => __( 'Search trials', NPC_TD ),
                'not_found'             => __( 'Trials not found', NPC_TD ),
                'not_found_in_trash'    => __( 'Not found in Trash', NPC_TD ),
                'featured_image'        => __( 'Trial Logo', NPC_TD ),
                'set_featured_image'    => __( 'Set trial logo', NPC_TD ),
                'remove_featured_image' => __( 'Remove trial logo', NPC_TD ),
                'use_featured_image'    => __( 'Use as trial logo', NPC_TD ),
                'insert_into_item'      => __( 'Insert into item', NPC_TD ),
                'uploaded_to_this_item' => __( 'Uploaded to this trial', NPC_TD ),
                'items_list'            => __( 'Trials list', NPC_TD ),
                'items_list_navigation' => __( 'Trials list navigation', NPC_TD ),
                'filter_items_list'     => __( 'Filter trials list', NPC_TD ),
            ]
        ]);
    }

    /**
     * Add Advanced Custom Fields
     */
    protected function addCustomFields()
    {
        if( function_exists('acf_add_local_field_group') ) {
            $ACFGroupLocation = [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => $this->CPTInstance->get('name'),
                    ],
                ],
            ];



            if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array(
                    'key' => 'group_5b8559fd1b56f',
                    'title' => 'ACF Group for Trials',
                    'fields' => array(
                        array(
                            'key' => 'field_5b855a0a14717',
                            'label' => 'Content',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'left',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_5bbdd8c76fbed',
                            'label' => 'Marketing title',
                            'name' => 'marketing_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'show_column' => 1,
                            'show_column_sortable' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5bbf25d8b8b0d',
                            'label' => 'Study title',
                            'name' => 'study_title',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 5,
                            'new_lines' => 'br',
                        ),
                        array(
                            'key' => 'field_5bb4cebb11ba2',
                            'label' => 'Title + City name',
                            'name' => 'title_+_city_name',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => 'br',
                        ),
                        array(
                            'key' => 'field_5b8807baee2bf',
                            'label' => 'Homepage Featured Trial',
                            'name' => 'featured_post',
                            'type' => 'checkbox',
                            'instructions' => 'This is Trial will be displayed on homepage like a featured trial.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'warning_acf',
                                'id' => '',
                            ),
                            'choices' => array(
                                'yes' => 'Feature this trial on homepage',
                            ),
                            'allow_custom' => 0,
                            'default_value' => array(
                            ),
                            'layout' => 'vertical',
                            'toggle' => 0,
                            'return_format' => 'value',
                            'save_custom' => 0,
                        ),
                        array(
                            'key' => 'field_5c617f8fac1b1',
                            'label' => 'Search Featured Trial',
                            'name' => 'search_featured_trial',
                            'type' => 'checkbox',
                            'instructions' => 'This is Trial will be displayed on top of search results like with a featured label',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'warning_acf',
                                'id' => '',
                            ),
                            'choices' => array(
                                'yes' => 'Show this trial on top of search results',
                            ),
                            'allow_custom' => 0,
                            'default_value' => array(
                            ),
                            'layout' => 'vertical',
                            'toggle' => 0,
                            'return_format' => 'value',
                            'save_custom' => 0,
                        ),
                        array(
                            'key' => 'field_5b90e8f18ac18',
                            'label' => 'Always show this trial',
                            'name' => 'show_all_this_trial',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'warning_acf__bottom',
                                'id' => '',
                            ),
                            'choices' => array(
                                'yes' => 'Always show',
                            ),
                            'allow_custom' => 0,
                            'default_value' => array(
                            ),
                            'layout' => 'vertical',
                            'toggle' => 0,
                            'return_format' => 'value',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                            'save_custom' => 0,
                        ),
                        array(
                            'key' => 'field_5c52c849278d0',
                            'label' => 'Short Description',
                            'name' => 'short_description',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 5,
                            'new_lines' => 'br',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5b9a2ebdfde68',
                            'label' => 'Brief Description',
                            'name' => 'the_trial_is_for_people',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'br',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5b9a2ed4fde69',
                            'label' => 'Study Goal',
                            'name' => 'participant_requirements',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'br',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5bb1dfe8cc77a',
                            'label' => 'What is involved for the Patient?',
                            'name' => 'involved',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'br',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5bb4d39f4b014',
                            'label' => 'Am I eligible?',
                            'name' => 'am_i_eligible',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 5,
                            'new_lines' => 'br',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5bb4d48b65083',
                            'label' => 'About the drug or intervention',
                            'name' => 'about_the_drug_or_intervention',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 7,
                            'new_lines' => 'br',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5bbc400c52914',
                            'label' => 'Trial is for people with',
                            'name' => 'trial_is_for_people_with',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 5,
                            'new_lines' => 'br',
                            'show_column' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                        ),
                        array(
                            'key' => 'field_5b8909bcc7235',
                            'label' => 'Location',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'left',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_5b87e9ff5b0c4',
                            'label' => 'Location',
                            'name' => 'location',
                            'type' => 'google_map',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'center_lat' => '',
                            'center_lng' => '',
                            'zoom' => '',
                            'height' => '',
                        ),
                        array(
                            'key' => 'field_5bbdf88e3fa44',
                            'label' => 'Location to display',
                            'name' => 'location_to_display',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b8909d7c7236',
                            'label' => 'Address and Contact info',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'left',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_5b9a33a01abd3',
                            'label' => 'Study Coordinator',
                            'name' => 'study_coordinator',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a33af1abd4',
                            'label' => 'Study Coordinator email',
                            'name' => 'study_coordinator_email',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a33b81abd5',
                            'label' => 'Study Coordinator phone',
                            'name' => 'study_coordinator_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a33c01abd6',
                            'label' => 'Site Name',
                            'name' => 'site_name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a33cc1abd7',
                            'label' => 'Address',
                            'name' => 'address',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a33d51abd8',
                            'label' => 'Sponsor',
                            'name' => 'sponsor',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a33e21abd9',
                            'label' => 'Study Drug',
                            'name' => 'study_drug',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a33fa1abda',
                            'label' => 'Estimated enrollment',
                            'name' => 'estimated_enrollment',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a34031abdb',
                            'label' => 'Estimated end date',
                            'name' => 'estimated_end_date',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5b9a3e2dfd380',
                            'label' => 'Currently Enrolling & Interventional',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'left',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_5b9a3e47fd381',
                            'label' => 'Currently Enrolling',
                            'name' => 'currently_enrolling',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '70',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                1 => 'Not yet recruiting',
                                3 => 'Currently Enrolling',
                                9 => 'Enrollment Closed',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'label',
                            'show_column' => 0,
                            'show_column_sortable' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_5b9a3ec5fd383',
                            'label' => 'Study type',
                            'name' => 'study_type',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '70',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                1 => 'Interventional',
                                2 => 'Observational',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'label',
                            'show_column' => 0,
                            'show_column_sortable' => 0,
                            'show_column_weight' => 1000,
                            'allow_quickedit' => 0,
                            'allow_bulkedit' => 1,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'trials',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                ));

            endif;
        }
    }


    public function addGoogleMapKey($api) {
        $api['key'] = 'AIzaSyDMJJTLIz11aIV8kywN-lhhfk0QI6AQulQ';
        return $api;
    }

//    public function addGoogleMapKey($api) {
//        $api['key'] = GMAPS_KEY;
//        return $api;
//    }

}